services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    aintreallydown\DepositBundle\Controller\PropertyController:
        arguments:
            $em: '@doctrine.orm.entity_manager'
        tags: ['controller.service_arguments']
        public: true

    aintreallydown\DepositBundle\Security\Voter\PropertyVoter:
        tags: ['security.voter']

    aintreallydown\DepositBundle\Form\PropertyFormType:
        tags: ['form.type']